### ISSUE TITLE
Menu button still visible when in desktop mode

### ISSUE THREAD

**Issue by ghost** [adnan1710/Notes-App#7]
Menu button for sidebar toggle is also visible even when the webpage is in desktop mode

**Comment by vijayusj** [comment]
i would like to work on this issue

**Comment by vijayusj** [comment]
include display equals to none on #sidebarBtn
#sidebarBtn
{
display:none;
}
and add display:block on 
@media only screen and (max-width: 768px) {
#sidebarBtn
{
display:block;
}
}
